name: Python Flake8 Code Quality

on:
  - push
  - pull_request

jobs:
  flake8:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install flake8==3.8.4
      - name: Run Flake8
        run: |
          flake8 --config=.flake8 --count --statistics --show-source --jobs=$(nproc) .
